name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Python test case
      id: python-test-case
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        setup-command: ''
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYTHON-TEST-CASE_RESULTS: "${{steps.python-test-case.outputs.result}}"
      with:
        runners: python-test-case
